version: '2.1'
orbs:
  maven: circleci/maven@1.4.1
workflows:
    example-workflow:
      jobs:
        - maven/test:
            test_results_path: target/surefire-reports
      steps:
        - run:
            name: Save test results
              command: |
                mkdir -p ~/test-results/junit/
                find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
              when: always
        - store_test_results:
              path: ~/test-results
